### ISSUE TITLE
PyPi Package out of date?

### ISSUE THREAD

**Issue by theced7** [cprieto/mdx_downheader#2]
Hi there,

I was trying for quite some time to get your extension to "down" more than one header. If I'm not mistaken, the PyPi package is still not using #1, is it? 
 
I'd really appreciate it if you took the time to update the package!

**Comment by cprieto** [comment]
Done, version 1.1.0 is published. Thanks mate! 👍

**Comment by theced7** [comment]
If there are any "thank yous" to be done, then it's the other way around! I appreciate the quick fix and of course the extension itself.
